### ISSUE TITLE
Unhandled exception when using wrong etcd address

### ISSUE THREAD

**Issue by robbrockbank** [projectcalico/libcalico#4]
Running calicoctl with an incorrect IP address results in stack trace showing a ConnectionTimeoutError (see stack trace).

We could fix up by catching this in calicoctl, but perhaps better to fix in datastore and rethrow the exception as a DataStoreError ?

calico@calicodev:~/calico-docker$ sudo ETCD_AUTHORITY=1.2.3.4:1234 ./calico_containers/calicoctl.py node
WARNING: Unable to detect the xt_set module. Load with `modprobe xt_set`
WARNING: Unable to detect the ipip module. Load with `modprobe ipip`
No IP provided. Using detected IP: 10.0.2.15
Unexpected error executing command.

Traceback (most recent call last):
  File "./calico_containers/calicoctl.py", line 101, in <module>
    getattr(command_module, command)(arguments)
  File "/home/calico/calico-docker/calico_containers/calico_ctl/node.py", line 164, in node
    kubernetes=arguments.get("--kubernetes"))
  File "/home/calico/calico-docker/calico_containers/calico_ctl/node.py", line 204, in node_start
    warn_if_hostname_conflict(ip)
  File "/home/calico/calico-docker/calico_containers/calico_ctl/node.py", line 391, in warn_if_hostname_conflict
    current_ipv4, _ = client().get_host_bgp_ips(hostname)
  File "/usr/local/lib/python2.7/dist-packages/pycalico/datastore.py", line 82, in wrapped
    return fn(_args, *_kwargs)
  File "/usr/local/lib/python2.7/dist-packages/pycalico/datastore.py", line 229, in get_host_bgp_ips
    ipv4 = self.etcd_client.read(bgp_ipv4).value
  File "/usr/local/lib/python2.7/dist-packages/etcd/client.py", line 356, in read
    timeout=timeout)
  File "/usr/local/lib/python2.7/dist-packages/etcd/client.py", line 582, in api_execute
    preload_content=False)
  File "/usr/local/lib/python2.7/dist-packages/urllib3/request.py", line 75, in request
    *_urlopen_kw)
  File "/usr/local/lib/python2.7/dist-packages/urllib3/request.py", line 88, in request_encode_url
    return self.urlopen(method, url, *_urlopen_kw)
  File "/usr/local/lib/python2.7/dist-packages/urllib3/poolmanager.py", line 155, in urlopen
    response = conn.urlopen(method, u.request_uri, **kw)
  File "/usr/local/lib/python2.7/dist-packages/urllib3/connectionpool.py", line 541, in urlopen
    body=body, headers=headers)
  File "/usr/local/lib/python2.7/dist-packages/urllib3/connectionpool.py", line 370, in _make_request
    (self.host, timeout_obj.connect_timeout))
ConnectTimeoutError: (<urllib3.connectionpool.HTTPConnectionPool object at 0x7fe8b80db550>, 'Connection to 1.2.3.4 timed out. (connect timeout=60)')

**Comment by alexhersh** [comment]
python-etcd v1.4.1 should handle HTTP errors as an EtcdException, which we _do_ catch in pycalico. The next libcalico release should include this change, but we need to test to make sure this case is handled.

**Comment by alexhersh** [comment]
exception now wrapped as follows in updated libcalico

```
sudo ETCD_AUTHORITY=1.2.3.4:1234 dist/calicoctl node
get_host_bgp_ips: Error accessing etcd (Connection to etcd failed due to
MaxRetryError("HTTPConnectionPool(host='1.2.3.4', port=1234): Max retries
exceeded with url: /v2/keys/calico/bgp/v1/host/metadev/ip_addr_v4 (Caused by
ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x2a0fb50>,
'Connection to 1.2.3.4 timed out. (connect timeout=60)'))",)).  Is etcd running?
```
